name: 'retail_dw'
version: '1.0.0'
config-version: 2

profile: 'retail_dw'

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


on-run-start:
  - "{{ ensure_stream_tables() }}"

models:
  retail_dw:
    gold:
      +materialized: table
      +schema: gold
    staging:
      +materialized: view
      +schema: staging
